sudo: required

services:
  - docker

language: java
dist: trusty

jdk:
  - openjdk8

cache:
  directories:
    - $HOME/.m2

env:
  - DOCKER_IMAGE=tomisebjanic/rso-users:0.4

script:
  - mvn clean package -U
  - docker build -t "$DOCKER_IMAGE" .

after_success:
  - docker login --username "$DOCKERHUB_USERNAME" --password "$DOCKERHUB_PASSWORD"
  - docker push "$DOCKER_IMAGE"