sudo: required

services:
  - docker

language: java
dist: trusty

jdk:
  - openjdk8

cache:
  directories:
    - $HOME/.m2

script:
  - mvn clean package -U
  - docker build -t tomisebjanic/rso-users .

after_success:
  - docker login --username "$DOCKERHUB_USERNAME" --password "$DOCKERHUB_PASSWORD"
  - docker push tomisebjanic/rso-users