version: "3"
services:
  rso-users:
    build: .
    ports:
      - 8082:8082
    environment:
      KUMULUZEE_DATASOURCES0_CONNECTIONURL: jdbc:postgresql://postgres:5432/rsouser
      KUMULUZEE_CONFIG_CONSUL_AGENT: http://consul:8500
      KUMULUZEE_DISCOVERY_CONSUL_AGENT: http://consul:8500
    depends_on:
      - postgres
      - consul
  postgres:
    image: postgres:10.0
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rsouser
  consul:
    image: consul
    ports:
      - 8400:8400
      - 8500:8500
      - 8600:8600
  accommodations:
    image: janerz6/accommodations
    ports:
      - 8081:8081
    environment:
      - CONFIG_SERVER_URL=http://consul:8500
      - DISCOVERY_HOSTNAME=accommodations
    depends_on:
      - consul
