kumuluzee:
  name: users
  version: 1.0.0
  env:
    name: dev
  datasources:
    - jndi-name: jdbc/UsersDS
      connection-url: jdbc:postgresql://localhost:5432/rsousers
      username: postgres
      password: postgres
      max-pool-size: 20
  server:
    base-url: http://localhost:8082
    http:
      port: 8082
  config:
    start-retry-delay-ms: 500
    max-retry-delay-ms: 900000
    etcd:
      hosts: http://localhost:2379
  discovery:
    ttl: 20
    ping-interval: 15
    etcd:
      hosts: http://localhost:2379
  health:
    servlet:
      mapping: /health
      enabled: true
    logs:
      enabled: true
      level: INFO
      period-s: 30
    checks:
      data-source-health-check:
        jndi-name: jdbc/UsersDS
      disk-space-health-check:
        threshold: 100000000
  cors-filter:
    servlet:
      allow-origin: "*"
  metrics:
    webinstrumentation:
      - name: metricsEndpoint
        url-pattern: /metrics/*
      - name: usersEndpoint
        url-pattern: /v1/users/*
  logs:
    config-file: '<?xml version="1.0" encoding="UTF-8"?>
                  <Configuration name="users">
                    <Appenders>
                      <Console name="console" target="SYSTEM_OUT">
                        <PatternLayout pattern="%d %p %marker %m %X %ex %n"/>
                      </Console>
                      <Socket name="logstash" host="d40c24bf-5206-4b4c-ba70-3275167a6e4b-ls.logit.io" port="17698" protocol="tcp">
                        <JSONLayout complete="false" compact="true" eventEol="true" charset="UTF-8" properties="true"/>
                      </Socket>
                    </Appenders>
                    <Loggers>
                      <Logger name="com.fri.rso.fririders.users.log" level="info" additivity="false">
                          <AppenderRef ref="console"/>
                      </Logger>
                      <Logger name="com.fri.rso.fririders.users.log" level="warn" additivity="false">
                          <AppenderRef ref="console"/>
                      </Logger>
                      <Logger name="com.fri.rso.fririders.users.log" level="trace" additivity="false">
                          <AppenderRef ref="console"/>
                      </Logger>
                      <Logger name="com.fri.rso.fririders.users.log" level="info" additivity="false">
                          <AppenderRef ref="logstash"/>
                      </Logger>
                      <Logger name="com.fri.rso.fririders.users.log" level="warn" additivity="false">
                          <AppenderRef ref="logstash"/>
                      </Logger>
                      <Logger name="com.fri.rso.fririders.users.log" level="trace" additivity="false">
                          <AppenderRef ref="logstash"/>
                      </Logger>
                      <!-- Default logger -->
                      <Root level="info">
                          <AppenderRef ref="console"/>
                          <AppenderRef ref="logstash"/>
                      </Root>
                    </Loggers>
                  </Configuration>'
  fault-tolerance:
    config:
      watch-enabled: true
      watch-properties: timeout.value,circuit-breaker.failure-ratio,bulkhead.value
    users:
      bulkhead:
        value: 5
      http-find-accommodations:
        timeout:
          value: 5000ms
        circuit-breaker:
          request-threshold: 10
          failure-ratio: 0.3
          delay: 3000ms
          metrics:
            rolling-window:
              size: 5s
              buckets: 5
      http-find-bookings:
        timeout:
          value: 5000ms
        circuit-breaker:
          request-threshold: 10
          failure-ratio: 0.3
          delay: 3000ms
          metrics:
            rolling-window:
              size: 5s
              buckets: 5
      http-auth-issue-jwt:
        timeout:
          value: 1000ms
        circuit-breaker:
          request-threshold: 10
          failure-ratio: 0.3
          delay: 3000ms
          metrics:
            rolling-window:
              size: 5s
              buckets: 5
      http-auth-verify-jwt:
        timeout:
          value: 1000ms
        circuit-breaker:
          request-threshold: 10
          failure-ratio: 0.3
          delay: 3000ms
          metrics:
            rolling-window:
              size: 5s
              buckets: 5


users-config:
  enable-registration: true
  enable-login: true
  password-min-length: 6
  healthy: true
