kumuluzee:
  name: rso-users
  version: 1.0.0
  env:
    name: dev
  datasources:
    - jndi-name: jdbc/UsersDS
      # connection-url: jdbc:postgresql://postgres:5432/rsousers
      connection-url: jdbc:postgresql://localhost:5432/rsousers
      username: postgres
      password: postgres
      max-pool-size: 20
  config:
    start-retry-delay-ms: 500
    max-retry-delay-ms: 900000
    consul:
      hosts: http://localhost:8500

users-config:
  enable-registration: true
  enable-login: true
  password-min-length: 6
