apiVersion: v1
kind: ReplicationController
metadata:
  name: consul-deployment
spec:
  replicas: 1
selector:
  app: consul
  template:
    metadata:
      labels:
        pool: consulpool
        app: consul
    spec:
      containers:
        - name: consul
          env:
            - name: ENVIRONMENT
              value: dev
            - name: MASTER_TOKEN
              value: INITIAL_MASTER_TOKEN_FOR_ACCESS
            - name: GOSSIP_KEY
              value: ENCRYPTION_KEY_FOR_GOSSIP
            - name: CONSUL_DEBUG
              value: true
            - name: CONSUL_SERVER_COUNT
              value: 1
          image: consul:1.0.0
          resources:
            limits:
              cpu: 1
              memory: 1024
          imagePullPolicy: Always
          ports:
          - containerPort: 8500
            name: ui-port
          - containerPort: 8400
            name: alt-port
          - containerPort: 53
            name: udp-port
          - containerPort: 8543
            name: https-port
          - containerPort: 8500
            name: http-port
          - containerPort: 8301
            name: serflan
          - containerPort: 8302
            name: serfwan
          - containerPort: 8600
            name: consuldns
          - containerPort: 8300
            name: server

---

apiVersion: v1
kind: Service
metadata:
  name: consul
spec:
  type: NodePort
  ports:
  - name: http
    port: 8500
  - name: rpc
    port: 8400
  - name: serflan
    port: 8301
  - name: serfwan
    port: 8302
  - name: server
    port: 8300
  - name: consuldns
    port: 8600
  selector:
    app: consulpool
