apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: users-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
      - image: tomisebjanic/rso-users:0.7
        name: users
        env:
          - name: KUMULUZEE_DISCOVERY_CLUSTER
            value: bluemix
          - name: KUMULUZEE_DISCOVERY_ETCD_HOSTS
            value: http://etcd:2379
          - name: KUMULUZEE_CONFIG_ETCD_HOSTS
            value: http://etcd:2379
          - name: KUMULUZEE_DATASOURCES0_CONNECTIONURL
            value: jdbc:postgresql://postgres:5432/rsousers
          - name: KUMULUZEE_SERVER_BASEURL
            value: http://users:8082
        livenessProbe:
          httpGet:
            path: /health
            port: server
          initialDelaySeconds: 60
          periodSeconds: 3
        ports:
        - containerPort: 8082
          name: server
          protocol: TCP
        resources:
          requests:
            cpu: 150m

---

apiVersion: v1
kind: Service
metadata:
  name: users
  labels:
    app: users
spec:
  type: NodePort
  ports:
  - name: server
    port: 8082
    protocol: TCP
    targetPort: 8082
  selector:
    app: users

---

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: users
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: users-deployment
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50